version: "3"

services:

  app:
    build: ./app
    container_name: demo_app

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    command:
      - -nginx.scrape-uri=http://nginx:80/stub_status
    ports:
      - "9113:9113"
    

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=24h"
    mem_limit: 400m
    cpus: 0.5


  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9110:9110"
    mem_limit: 50m
    cpus: 0.1


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    mem_limit: 200m
    cpus: 0.3


  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    volumes:
      - loki_data:/loki
    mem_limit: 300m
    cpus: 0.3


  alloy:
    image: grafana/alloy:latest
    container_name: grafana_alloy
    volumes:
      - ./logging/config.alloy:/etc/alloy/config.alloy
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: run /etc/alloy/config.alloy

  cadvisor: 
    image: gcr.io/cadvisor/cadvisor:latest 
    container_name: cadvisor 
    ports: 
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro 
    privileged: true 
    mem_limit: 100m
    cpus: 0.2

volumes:
  grafana_data:
  prometheus_data:
  loki_data: