stages:
  - build
  - push
  - deploy

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind

  script:
    - docker build -t devops-platform .

push_image:
  stage: push
  script:
    - docker tag devops-platform registry/devops-platform
    - docker push registry/devops-platform

deploy:
  stage: deploy
  script:
    - ssh server "docker pull registry/devops-platform"
    - ssh server "docker compose up -d"